version: '3.8'

services:
  trip-tracker-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=your-super-secret-key-change-this-in-production
      - DATABASE_URL=sqlite:///./data/trip_tracker.db
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3